const fs = require('fs');

// All game data in the exact format expected by the C# models
// Models expect: int IDs, specific field names (def not defense, etc.)

// ---- MONSTERS ----
const monsters = [
  { id: 1,  name: "Araña",          level: 2,  hp: 40,   atkMin: 6,  atkMax: 8,   def: 1,  atkRate: 8,   defRate: 1,   xp: 5,    aggroRange: 3, attackRange: 1, moveSpeed: 2, respawnTime: 15, drops: [{ itemDefId: 1, chance: 0.3, minLevel: 0, maxLevel: 3 }] },
  { id: 2,  name: "Budge Dragon",   level: 4,  hp: 85,   atkMin: 10, atkMax: 15,  def: 3,  atkRate: 12,  defRate: 4,   xp: 12,   aggroRange: 4, attackRange: 1, moveSpeed: 3, respawnTime: 15, drops: [{ itemDefId: 2, chance: 0.25, minLevel: 0, maxLevel: 3 }] },
  { id: 3,  name: "Bull Fighter",   level: 6,  hp: 130,  atkMin: 14, atkMax: 22,  def: 5,  atkRate: 16,  defRate: 7,   xp: 22,   aggroRange: 4, attackRange: 1, moveSpeed: 2, respawnTime: 18, drops: [{ itemDefId: 3, chance: 0.2, minLevel: 0, maxLevel: 4 }] },
  { id: 4,  name: "Hound",          level: 8,  hp: 180,  atkMin: 18, atkMax: 28,  def: 7,  atkRate: 20,  defRate: 10,  xp: 35,   aggroRange: 5, attackRange: 1, moveSpeed: 3, respawnTime: 18, drops: [{ itemDefId: 4, chance: 0.2, minLevel: 0, maxLevel: 4 }] },
  { id: 5,  name: "Giant",          level: 10, hp: 250,  atkMin: 22, atkMax: 35,  def: 9,  atkRate: 24,  defRate: 13,  xp: 50,   aggroRange: 5, attackRange: 2, moveSpeed: 1, respawnTime: 20, drops: [{ itemDefId: 5, chance: 0.18, minLevel: 0, maxLevel: 5 }] },
  { id: 6,  name: "Goblin",         level: 12, hp: 320,  atkMin: 26, atkMax: 40,  def: 11, atkRate: 28,  defRate: 16,  xp: 70,   aggroRange: 5, attackRange: 1, moveSpeed: 2, respawnTime: 20, drops: [{ itemDefId: 6, chance: 0.15, minLevel: 0, maxLevel: 5 }] },
  { id: 7,  name: "Stone Golem",    level: 15, hp: 450,  atkMin: 32, atkMax: 50,  def: 15, atkRate: 32,  defRate: 20,  xp: 110,  aggroRange: 6, attackRange: 2, moveSpeed: 1, respawnTime: 25, drops: [{ itemDefId: 7, chance: 0.2, minLevel: 0, maxLevel: 6 }] },
  { id: 8,  name: "Ghost",          level: 18, hp: 550,  atkMin: 38, atkMax: 58,  def: 18, atkRate: 36,  defRate: 24,  xp: 160,  aggroRange: 6, attackRange: 1, moveSpeed: 2, respawnTime: 25, drops: [{ itemDefId: 8, chance: 0.18, minLevel: 0, maxLevel: 6 }] },
  { id: 9,  name: "Skeleton",       level: 20, hp: 650,  atkMin: 42, atkMax: 65,  def: 20, atkRate: 40,  defRate: 27,  xp: 200,  aggroRange: 6, attackRange: 1, moveSpeed: 2, respawnTime: 25, drops: [{ itemDefId: 9, chance: 0.15, minLevel: 0, maxLevel: 7 }] },
  { id: 10, name: "Yeti",           level: 23, hp: 800,  atkMin: 48, atkMax: 72,  def: 24, atkRate: 44,  defRate: 30,  xp: 260,  aggroRange: 7, attackRange: 1, moveSpeed: 2, respawnTime: 28, drops: [{ itemDefId: 10, chance: 0.15, minLevel: 0, maxLevel: 7 }] },
  { id: 11, name: "Ice Queen",      level: 28, hp: 1100, atkMin: 58, atkMax: 88,  def: 30, atkRate: 50,  defRate: 36,  xp: 380,  aggroRange: 7, attackRange: 2, moveSpeed: 2, respawnTime: 30, drops: [{ itemDefId: 11, chance: 0.12, minLevel: 0, maxLevel: 8 }] },
  { id: 12, name: "Gorgon",         level: 32, hp: 1500, atkMin: 68, atkMax: 102, def: 35, atkRate: 55,  defRate: 42,  xp: 520,  aggroRange: 7, attackRange: 2, moveSpeed: 2, respawnTime: 30, drops: [{ itemDefId: 12, chance: 0.1, minLevel: 0, maxLevel: 8 }] },
  { id: 13, name: "Balrog",         level: 36, hp: 2000, atkMin: 80, atkMax: 120, def: 40, atkRate: 60,  defRate: 48,  xp: 700,  aggroRange: 8, attackRange: 2, moveSpeed: 3, respawnTime: 35, drops: [{ itemDefId: 13, chance: 0.08, minLevel: 0, maxLevel: 9 }] },
  { id: 14, name: "Death Angel",    level: 40, hp: 2600, atkMin: 90, atkMax: 135, def: 45, atkRate: 65,  defRate: 54,  xp: 900,  aggroRange: 8, attackRange: 1, moveSpeed: 3, respawnTime: 35, drops: [{ itemDefId: 14, chance: 0.08, minLevel: 0, maxLevel: 9 }] },
  { id: 15, name: "Death Knight",   level: 45, hp: 3500, atkMin: 105, atkMax: 155, def: 52, atkRate: 72,  defRate: 60,  xp: 1200, aggroRange: 8, attackRange: 1, moveSpeed: 3, respawnTime: 30, drops: [{ itemDefId: 15, chance: 0.06, minLevel: 0, maxLevel: 10 }] },
  { id: 16, name: "Worm",           level: 3,  hp: 60,   atkMin: 7,  atkMax: 12,  def: 2,  atkRate: 10,  defRate: 3,   xp: 8,    aggroRange: 2, attackRange: 1, moveSpeed: 1, respawnTime: 12, drops: [{ itemDefId: 1, chance: 0.35, minLevel: 0, maxLevel: 2 }] },
  { id: 17, name: "Shadow",         level: 14, hp: 380,  atkMin: 28, atkMax: 44,  def: 12, atkRate: 30,  defRate: 18,  xp: 85,   aggroRange: 6, attackRange: 1, moveSpeed: 3, respawnTime: 22, drops: [{ itemDefId: 7, chance: 0.18, minLevel: 0, maxLevel: 5 }] },
  { id: 18, name: "Elite Goblin",   level: 16, hp: 500,  atkMin: 35, atkMax: 52,  def: 16, atkRate: 34,  defRate: 22,  xp: 130,  aggroRange: 6, attackRange: 1, moveSpeed: 2, respawnTime: 22, drops: [{ itemDefId: 8, chance: 0.15, minLevel: 0, maxLevel: 6 }] },
  { id: 19, name: "Elite Skeleton", level: 22, hp: 750,  atkMin: 45, atkMax: 68,  def: 22, atkRate: 42,  defRate: 28,  xp: 230,  aggroRange: 7, attackRange: 1, moveSpeed: 2, respawnTime: 28, drops: [{ itemDefId: 10, chance: 0.12, minLevel: 0, maxLevel: 7 }] },
  { id: 20, name: "Mutant",         level: 25, hp: 950,  atkMin: 52, atkMax: 78,  def: 26, atkRate: 46,  defRate: 32,  xp: 300,  aggroRange: 7, attackRange: 2, moveSpeed: 2, respawnTime: 28, drops: [{ itemDefId: 11, chance: 0.1, minLevel: 0, maxLevel: 8 }] },
  { id: 21, name: "Elite Yeti",     level: 30, hp: 1300, atkMin: 62, atkMax: 94,  def: 32, atkRate: 52,  defRate: 38,  xp: 450,  aggroRange: 7, attackRange: 1, moveSpeed: 2, respawnTime: 30, drops: [{ itemDefId: 12, chance: 0.1, minLevel: 0, maxLevel: 8 }] },
  { id: 22, name: "Cursed Wizard",  level: 34, hp: 1800, atkMin: 74, atkMax: 110, def: 38, atkRate: 58,  defRate: 44,  xp: 620,  aggroRange: 8, attackRange: 3, moveSpeed: 2, respawnTime: 32, drops: [{ itemDefId: 14, chance: 0.08, minLevel: 0, maxLevel: 9 }] },
  { id: 23, name: "Elite Golem",    level: 38, hp: 2400, atkMin: 85, atkMax: 128, def: 44, atkRate: 62,  defRate: 50,  xp: 820,  aggroRange: 8, attackRange: 2, moveSpeed: 1, respawnTime: 35, drops: [{ itemDefId: 15, chance: 0.06, minLevel: 0, maxLevel: 9 }] },
  { id: 24, name: "Devil",          level: 42, hp: 3000, atkMin: 96, atkMax: 142, def: 48, atkRate: 68,  defRate: 56,  xp: 1050, aggroRange: 8, attackRange: 2, moveSpeed: 3, respawnTime: 35, drops: [{ itemDefId: 16, chance: 0.05, minLevel: 0, maxLevel: 10 }] },
  { id: 25, name: "Hell Hound",     level: 3,  hp: 55,   atkMin: 7,  atkMax: 11,  def: 2,  atkRate: 10,  defRate: 3,   xp: 9,    aggroRange: 4, attackRange: 1, moveSpeed: 3, respawnTime: 12, drops: [{ itemDefId: 1, chance: 0.3, minLevel: 0, maxLevel: 2 }] },
  { id: 26, name: "Thunder Golem",  level: 35, hp: 2200, atkMin: 78, atkMax: 118, def: 42, atkRate: 60,  defRate: 46,  xp: 750,  aggroRange: 8, attackRange: 3, moveSpeed: 1, respawnTime: 30, drops: [{ itemDefId: 15, chance: 0.06, minLevel: 0, maxLevel: 9 }] },
  { id: 27, name: "Death Rider",    level: 48, hp: 4000, atkMin: 112, atkMax: 165, def: 55, atkRate: 76,  defRate: 64,  xp: 1400, aggroRange: 9, attackRange: 1, moveSpeed: 3, respawnTime: 30, drops: [{ itemDefId: 17, chance: 0.04, minLevel: 0, maxLevel: 10 }] },
  { id: 28, name: "Lich",           level: 50, hp: 4500, atkMin: 120, atkMax: 175, def: 58, atkRate: 80,  defRate: 68,  xp: 1600, aggroRange: 9, attackRange: 4, moveSpeed: 2, respawnTime: 30, drops: [{ itemDefId: 18, chance: 0.04, minLevel: 0, maxLevel: 10 }] },
  { id: 29, name: "Fire Golem",     level: 44, hp: 3200, atkMin: 100, atkMax: 148, def: 50, atkRate: 70,  defRate: 58,  xp: 1100, aggroRange: 8, attackRange: 2, moveSpeed: 1, respawnTime: 35, drops: [{ itemDefId: 16, chance: 0.05, minLevel: 0, maxLevel: 10 }] },
  { id: 30, name: "Queen Bee",      level: 7,  hp: 150,  atkMin: 15, atkMax: 24,  def: 6,  atkRate: 18,  defRate: 8,   xp: 28,   aggroRange: 4, attackRange: 1, moveSpeed: 3, respawnTime: 16, drops: [{ itemDefId: 3, chance: 0.22, minLevel: 0, maxLevel: 4 }] },
  { id: 31, name: "Dark Elf",       level: 26, hp: 1000, atkMin: 55, atkMax: 82,  def: 28, atkRate: 48,  defRate: 34,  xp: 340,  aggroRange: 7, attackRange: 2, moveSpeed: 3, respawnTime: 28, drops: [{ itemDefId: 11, chance: 0.1, minLevel: 0, maxLevel: 8 }] },
  { id: 32, name: "Ice Giant",      level: 33, hp: 1700, atkMin: 72, atkMax: 108, def: 38, atkRate: 56,  defRate: 42,  xp: 580,  aggroRange: 7, attackRange: 2, moveSpeed: 1, respawnTime: 30, drops: [{ itemDefId: 13, chance: 0.08, minLevel: 0, maxLevel: 9 }] },
  { id: 33, name: "Demon",          level: 46, hp: 3800, atkMin: 108, atkMax: 160, def: 54, atkRate: 74,  defRate: 62,  xp: 1300, aggroRange: 9, attackRange: 2, moveSpeed: 3, respawnTime: 30, drops: [{ itemDefId: 17, chance: 0.04, minLevel: 0, maxLevel: 10 }] },
  { id: 34, name: "Dark Lord",      level: 52, hp: 5000, atkMin: 130, atkMax: 190, def: 62, atkRate: 84,  defRate: 72,  xp: 1800, aggroRange: 9, attackRange: 2, moveSpeed: 3, respawnTime: 30, drops: [{ itemDefId: 18, chance: 0.03, minLevel: 0, maxLevel: 10 }] },
  { id: 35, name: "Phoenix",        level: 55, hp: 6000, atkMin: 145, atkMax: 210, def: 68, atkRate: 88,  defRate: 76,  xp: 2200, aggroRange: 9, attackRange: 3, moveSpeed: 4, respawnTime: 30, drops: [{ itemDefId: 19, chance: 0.02, minLevel: 0, maxLevel: 10 }] },
  { id: 36, name: "Hydra",          level: 60, hp: 8000, atkMin: 165, atkMax: 240, def: 75, atkRate: 95,  defRate: 82,  xp: 3000, aggroRange: 10, attackRange: 3, moveSpeed: 3, respawnTime: 30, drops: [{ itemDefId: 20, chance: 0.01, minLevel: 0, maxLevel: 10 }] },
];

// ---- ITEMS ----
const items = [
  { id: 1,  name: "Poción HP Pequeña",    type: "potion",  class: "all",  slot: "consumable", level: 0,  reqStr: 0, reqAgi: 0, reqVit: 0, reqEne: 0, attackMin: 0, attackMax: 0, defense: 0, wizRaise: 0, speed: 0, luck: false, value: 10,  icon: 1,  healHp: 50,  healMp: 0 },
  { id: 2,  name: "Poción HP Mediana",    type: "potion",  class: "all",  slot: "consumable", level: 0,  reqStr: 0, reqAgi: 0, reqVit: 0, reqEne: 0, attackMin: 0, attackMax: 0, defense: 0, wizRaise: 0, speed: 0, luck: false, value: 30,  icon: 2,  healHp: 150, healMp: 0 },
  { id: 3,  name: "Poción HP Grande",     type: "potion",  class: "all",  slot: "consumable", level: 0,  reqStr: 0, reqAgi: 0, reqVit: 0, reqEne: 0, attackMin: 0, attackMax: 0, defense: 0, wizRaise: 0, speed: 0, luck: false, value: 70,  icon: 3,  healHp: 400, healMp: 0 },
  { id: 4,  name: "Poción MP Pequeña",    type: "potion",  class: "all",  slot: "consumable", level: 0,  reqStr: 0, reqAgi: 0, reqVit: 0, reqEne: 0, attackMin: 0, attackMax: 0, defense: 0, wizRaise: 0, speed: 0, luck: false, value: 10,  icon: 4,  healHp: 0,   healMp: 40 },
  { id: 5,  name: "Poción MP Mediana",    type: "potion",  class: "all",  slot: "consumable", level: 0,  reqStr: 0, reqAgi: 0, reqVit: 0, reqEne: 0, attackMin: 0, attackMax: 0, defense: 0, wizRaise: 0, speed: 0, luck: false, value: 30,  icon: 5,  healHp: 0,   healMp: 120 },
  { id: 6,  name: "Poción MP Grande",     type: "potion",  class: "all",  slot: "consumable", level: 0,  reqStr: 0, reqAgi: 0, reqVit: 0, reqEne: 0, attackMin: 0, attackMax: 0, defense: 0, wizRaise: 0, speed: 0, luck: false, value: 70,  icon: 6,  healHp: 0,   healMp: 300 },
  { id: 7,  name: "Espada Corta",         type: "weapon",  class: "dk",   slot: "rightHand",   level: 1,  reqStr: 15, reqAgi: 10, reqVit: 0, reqEne: 0, attackMin: 4,  attackMax: 8,  defense: 0, wizRaise: 0, speed: 20, luck: false, value: 50,  icon: 10, healHp: 0,   healMp: 0 },
  { id: 8,  name: "Espada Larga",         type: "weapon",  class: "dk",   slot: "rightHand",   level: 3,  reqStr: 25, reqAgi: 15, reqVit: 0, reqEne: 0, attackMin: 8,  attackMax: 14, defense: 0, wizRaise: 0, speed: 25, luck: false, value: 150, icon: 11, healHp: 0,   healMp: 0 },
  { id: 9,  name: "Hoja",                 type: "weapon",  class: "dk",   slot: "rightHand",   level: 5,  reqStr: 40, reqAgi: 25, reqVit: 0, reqEne: 0, attackMin: 14, attackMax: 22, defense: 0, wizRaise: 0, speed: 30, luck: false, value: 400, icon: 12, healHp: 0,   healMp: 0 },
  { id: 10, name: "Espada Bastarda",      type: "weapon",  class: "dk",   slot: "rightHand",   level: 8,  reqStr: 60, reqAgi: 35, reqVit: 0, reqEne: 0, attackMin: 20, attackMax: 32, defense: 0, wizRaise: 0, speed: 25, luck: false, value: 800, icon: 13, healHp: 0,   healMp: 0 },
  { id: 11, name: "Gran Espada",          type: "weapon",  class: "dk",   slot: "twoHand",     level: 12, reqStr: 90, reqAgi: 50, reqVit: 0, reqEne: 0, attackMin: 30, attackMax: 48, defense: 0, wizRaise: 0, speed: 20, luck: false, value: 1500, icon: 14, healHp: 0,   healMp: 0 },
  { id: 12, name: "Arco Corto",           type: "weapon",  class: "elf",  slot: "rightHand",   level: 1,  reqStr: 10, reqAgi: 20, reqVit: 0, reqEne: 0, attackMin: 3,  attackMax: 7,  defense: 0, wizRaise: 0, speed: 25, luck: false, value: 50,  icon: 15, healHp: 0,   healMp: 0 },
  { id: 13, name: "Arco Largo",           type: "weapon",  class: "elf",  slot: "rightHand",   level: 3,  reqStr: 15, reqAgi: 35, reqVit: 0, reqEne: 0, attackMin: 7,  attackMax: 13, defense: 0, wizRaise: 0, speed: 30, luck: false, value: 150, icon: 16, healHp: 0,   healMp: 0 },
  { id: 14, name: "Ballesta",             type: "weapon",  class: "elf",  slot: "rightHand",   level: 6,  reqStr: 20, reqAgi: 55, reqVit: 0, reqEne: 0, attackMin: 12, attackMax: 20, defense: 0, wizRaise: 0, speed: 25, luck: false, value: 500, icon: 17, healHp: 0,   healMp: 0 },
  { id: 15, name: "Arco de Plata",        type: "weapon",  class: "elf",  slot: "rightHand",   level: 10, reqStr: 30, reqAgi: 80, reqVit: 0, reqEne: 0, attackMin: 20, attackMax: 34, defense: 0, wizRaise: 0, speed: 30, luck: false, value: 1200, icon: 18, healHp: 0,   healMp: 0 },
  { id: 16, name: "Arco Supremo",        type: "weapon",  class: "elf",  slot: "rightHand",   level: 14, reqStr: 40, reqAgi: 120,reqVit: 0, reqEne: 0, attackMin: 32, attackMax: 50, defense: 0, wizRaise: 0, speed: 35, luck: false, value: 2500, icon: 19, healHp: 0,   healMp: 0 },
  { id: 17, name: "Bastón de Madera",     type: "weapon",  class: "mago", slot: "rightHand",   level: 1,  reqStr: 10, reqAgi: 0,  reqVit: 0, reqEne: 25, attackMin: 3,  attackMax: 6,  defense: 0, wizRaise: 5,  speed: 15, luck: false, value: 60,  icon: 20, healHp: 0,   healMp: 0 },
  { id: 18, name: "Bastón de Hueso",      type: "weapon",  class: "mago", slot: "rightHand",   level: 3,  reqStr: 15, reqAgi: 0,  reqVit: 0, reqEne: 45, attackMin: 6,  attackMax: 11, defense: 0, wizRaise: 10, speed: 15, luck: false, value: 180, icon: 21, healHp: 0,   healMp: 0 },
  { id: 19, name: "Bastón de Cristal",    type: "weapon",  class: "mago", slot: "rightHand",   level: 6,  reqStr: 20, reqAgi: 0,  reqVit: 0, reqEne: 70, attackMin: 10, attackMax: 18, defense: 0, wizRaise: 18, speed: 20, luck: false, value: 600, icon: 22, healHp: 0,   healMp: 0 },
  { id: 20, name: "Bastón de Rubí",       type: "weapon",  class: "mago", slot: "rightHand",   level: 10, reqStr: 25, reqAgi: 0,  reqVit: 0, reqEne: 110,attackMin: 18, attackMax: 30, defense: 0, wizRaise: 28, speed: 20, luck: false, value: 1500, icon: 23, healHp: 0,   healMp: 0 },
  { id: 21, name: "Bastón Élite",         type: "weapon",  class: "mago", slot: "rightHand",   level: 14, reqStr: 30, reqAgi: 0,  reqVit: 0, reqEne: 160,attackMin: 28, attackMax: 44, defense: 0, wizRaise: 40, speed: 20, luck: false, value: 3000, icon: 24, healHp: 0,   healMp: 0 },
  { id: 22, name: "Casco de Cuero",       type: "armor",   class: "dk",   slot: "head",        level: 1,  reqStr: 15, reqAgi: 10, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 3, wizRaise: 0, speed: 0,  luck: false, value: 60,  icon: 30, healHp: 0,   healMp: 0 },
  { id: 23, name: "Armadura de Cuero",    type: "armor",   class: "dk",   slot: "chest",       level: 1,  reqStr: 18, reqAgi: 10, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 6, wizRaise: 0, speed: 0,  luck: false, value: 150, icon: 31, healHp: 0,   healMp: 0 },
  { id: 24, name: "Pantalones de Cuero",  type: "armor",   class: "dk",   slot: "legs",        level: 1,  reqStr: 16, reqAgi: 10, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 4, wizRaise: 0, speed: 0,  luck: false, value: 90,  icon: 32, healHp: 0,   healMp: 0 },
  { id: 25, name: "Guantes de Cuero",     type: "armor",   class: "dk",   slot: "hands",       level: 1,  reqStr: 14, reqAgi: 10, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 2, wizRaise: 0, speed: 0,  luck: false, value: 40,  icon: 33, healHp: 0,   healMp: 0 },
  { id: 26, name: "Botas de Cuero",       type: "armor",   class: "dk",   slot: "feet",        level: 1,  reqStr: 14, reqAgi: 10, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 2, wizRaise: 0, speed: 0,  luck: false, value: 40,  icon: 34, healHp: 0,   healMp: 0 },
  { id: 27, name: "Casco de Bronce",      type: "armor",   class: "dk",   slot: "head",        level: 3,  reqStr: 30, reqAgi: 15, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 5, wizRaise: 0, speed: 0,  luck: false, value: 200, icon: 35, healHp: 0,   healMp: 0 },
  { id: 28, name: "Armadura de Bronce",   type: "armor",   class: "dk",   slot: "chest",       level: 3,  reqStr: 35, reqAgi: 15, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 10, wizRaise: 0, speed: 0, luck: false, value: 500, icon: 36, healHp: 0,   healMp: 0 },
  { id: 29, name: "Pantalones de Bronce", type: "armor",   class: "dk",   slot: "legs",        level: 3,  reqStr: 32, reqAgi: 15, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 6, wizRaise: 0, speed: 0,  luck: false, value: 300, icon: 37, healHp: 0,   healMp: 0 },
  { id: 30, name: "Guantes de Bronce",    type: "armor",   class: "dk",   slot: "hands",       level: 3,  reqStr: 28, reqAgi: 15, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 3, wizRaise: 0, speed: 0,  luck: false, value: 150, icon: 38, healHp: 0,   healMp: 0 },
  { id: 31, name: "Botas de Bronce",      type: "armor",   class: "dk",   slot: "feet",        level: 3,  reqStr: 28, reqAgi: 15, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 3, wizRaise: 0, speed: 0,  luck: false, value: 150, icon: 39, healHp: 0,   healMp: 0 },
  { id: 32, name: "Casco de Escamas",     type: "armor",   class: "dk",   slot: "head",        level: 6,  reqStr: 50, reqAgi: 25, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 8, wizRaise: 0, speed: 0,  luck: false, value: 600, icon: 40, healHp: 0,   healMp: 0 },
  { id: 33, name: "Armadura de Escamas",  type: "armor",   class: "dk",   slot: "chest",       level: 6,  reqStr: 55, reqAgi: 25, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 14, wizRaise: 0, speed: 0, luck: false, value: 1500, icon: 41, healHp: 0,   healMp: 0 },
  { id: 34, name: "Casco de Mithril",     type: "armor",   class: "dk",   slot: "head",        level: 10, reqStr: 80, reqAgi: 40, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 12, wizRaise: 0, speed: 0, luck: false, value: 1500, icon: 42, healHp: 0,   healMp: 0 },
  { id: 35, name: "Armadura de Mithril",  type: "armor",   class: "dk",   slot: "chest",       level: 10, reqStr: 90, reqAgi: 40, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 20, wizRaise: 0, speed: 0, luck: false, value: 3500, icon: 43, healHp: 0,   healMp: 0 },
  { id: 36, name: "Casco de Dragon",      type: "armor",   class: "dk",   slot: "head",        level: 14, reqStr: 120, reqAgi: 60, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 16, wizRaise: 0, speed: 0, luck: false, value: 3000, icon: 44, healHp: 0,   healMp: 0 },
  { id: 37, name: "Armadura de Dragon",   type: "armor",   class: "dk",   slot: "chest",       level: 14, reqStr: 130, reqAgi: 60, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 28, wizRaise: 0, speed: 0, luck: false, value: 7000, icon: 45, healHp: 0,   healMp: 0 },
  { id: 38, name: "Casco de Elfos",       type: "armor",   class: "elf",  slot: "head",        level: 2,  reqStr: 10, reqAgi: 25, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 2, wizRaise: 0, speed: 0,  luck: false, value: 80,  icon: 46, healHp: 0,   healMp: 0 },
  { id: 39, name: "Armadura de Elfos",    type: "armor",   class: "elf",  slot: "chest",       level: 2,  reqStr: 12, reqAgi: 30, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 5, wizRaise: 0, speed: 0,  luck: false, value: 200, icon: 47, healHp: 0,   healMp: 0 },
  { id: 40, name: "Casco de Magos",       type: "armor",   class: "mago", slot: "head",        level: 2,  reqStr: 8,  reqAgi: 0,  reqVit: 0, reqEne: 30, attackMin: 0,  attackMax: 0,  defense: 1, wizRaise: 0, speed: 0,  luck: false, value: 70,  icon: 48, healHp: 0,   healMp: 0 },
  { id: 41, name: "Armadura de Magos",    type: "armor",   class: "mago", slot: "chest",       level: 2,  reqStr: 10, reqAgi: 0,  reqVit: 0, reqEne: 40, attackMin: 0,  attackMax: 0,  defense: 3, wizRaise: 0, speed: 0,  luck: false, value: 180, icon: 49, healHp: 0,   healMp: 0 },
  { id: 42, name: "Escudo Pequeño",       type: "armor",   class: "dk",   slot: "leftHand",    level: 1,  reqStr: 12, reqAgi: 8,  reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 4, wizRaise: 0, speed: 0,  luck: false, value: 30,  icon: 50, healHp: 0,   healMp: 0 },
  { id: 43, name: "Escudo de Bronce",     type: "armor",   class: "dk",   slot: "leftHand",    level: 3,  reqStr: 25, reqAgi: 15, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 7, wizRaise: 0, speed: 0,  luck: false, value: 120, icon: 51, healHp: 0,   healMp: 0 },
  { id: 44, name: "Alas de DK",           type: "wing",    class: "dk",   slot: "wings",       level: 15, reqStr: 100, reqAgi: 50, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 10, wizRaise: 0, speed: 0, luck: false, value: 5000, icon: 60, healHp: 0,   healMp: 0 },
  { id: 45, name: "Alas de Elf",          type: "wing",    class: "elf",  slot: "wings",       level: 15, reqStr: 30, reqAgi: 120, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 8, wizRaise: 0, speed: 0,  luck: false, value: 5000, icon: 61, healHp: 0,   healMp: 0 },
  { id: 46, name: "Alas de Mago",         type: "wing",    class: "mago", slot: "wings",       level: 15, reqStr: 30, reqAgi: 0,  reqVit: 0, reqEne: 120, attackMin: 0,  attackMax: 0,  defense: 6, wizRaise: 10, speed: 0, luck: false, value: 5000, icon: 62, healHp: 0,   healMp: 0 },
  { id: 47, name: "Joya de Bendición",    type: "jewel",   class: "all",  slot: "jewel",       level: 0,  reqStr: 0,  reqAgi: 0,  reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 0, wizRaise: 0, speed: 0,  luck: false, value: 10000, icon: 70, healHp: 0,   healMp: 0 },
  { id: 48, name: "Joya de Alma",         type: "jewel",   class: "all",  slot: "jewel",       level: 0,  reqStr: 0,  reqAgi: 0,  reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 0, wizRaise: 0, speed: 0,  luck: false, value: 15000, icon: 71, healHp: 0,   healMp: 0 },
  { id: 49, name: "Joya del Caos",        type: "jewel",   class: "all",  slot: "jewel",       level: 0,  reqStr: 0,  reqAgi: 0,  reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 0, wizRaise: 0, speed: 0,  luck: false, value: 20000, icon: 72, healHp: 0,   healMp: 0 },
  { id: 50, name: "Flechas",              type: "ammo",    class: "elf",  slot: "quiver",      level: 1,  reqStr: 0,  reqAgi: 15, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 0, wizRaise: 0, speed: 0,  luck: false, value: 5,   icon: 80, healHp: 0,   healMp: 0 },
  { id: 51, name: "Bombas",               type: "ammo",    class: "elf",  slot: "quiver",      level: 3,  reqStr: 0,  reqAgi: 30, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 0, wizRaise: 0, speed: 0,  luck: false, value: 10,  icon: 81, healHp: 0,   healMp: 0 },
  { id: 52, name: "Anillo de Fuerza",     type: "ring",    class: "all",  slot: "ring",        level: 5,  reqStr: 0,  reqAgi: 0,  reqVit: 0, reqEne: 0, attackMin: 4,  attackMax: 8,  defense: 0, wizRaise: 0, speed: 0,  luck: false, value: 500, icon: 90, healHp: 0,   healMp: 0 },
  { id: 53, name: "Anillo de Magia",      type: "ring",    class: "all",  slot: "ring",        level: 5,  reqStr: 0,  reqAgi: 0,  reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 0, wizRaise: 10, speed: 0, luck: false, value: 500, icon: 91, healHp: 0,   healMp: 0 },
  { id: 54, name: "Anillo de Protección", type: "ring",    class: "all",  slot: "ring",        level: 5,  reqStr: 0,  reqAgi: 0,  reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 8, wizRaise: 0, speed: 0,  luck: false, value: 500, icon: 92, healHp: 0,   healMp: 0 },
  { id: 55, name: "Pendiente de Fuerza",  type: "pendant", class: "all",  slot: "pendant",     level: 10, reqStr: 0,  reqAgi: 0,  reqVit: 0, reqEne: 0, attackMin: 8,  attackMax: 16, defense: 0, wizRaise: 0, speed: 0, luck: false, value: 1500, icon: 93, healHp: 0,   healMp: 0 },
  { id: 56, name: "Pendiente de Magia",   type: "pendant", class: "all",  slot: "pendant",     level: 10, reqStr: 0,  reqAgi: 0,  reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 0, wizRaise: 20, speed: 0, luck: false, value: 1500, icon: 94, healHp: 0,   healMp: 0 },
  { id: 57, name: "Pergamino de Poder",   type: "scroll",  class: "all",  slot: "consumable", level: 0,  reqStr: 0,  reqAgi: 0,  reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 0, wizRaise: 0, speed: 0,  luck: false, value: 100, icon: 95, healHp: 0,   healMp: 0 },
  { id: 58, name: "Poción de Velocidad",  type: "potion",  class: "all",  slot: "consumable", level: 0,  reqStr: 0,  reqAgi: 0,  reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 0, wizRaise: 0, speed: 30, luck: false, value: 50,  icon: 96, healHp: 0,   healMp: 0 },
  { id: 59, name: "Escudo de Dragón",     type: "armor",   class: "dk",   slot: "leftHand",    level: 12, reqStr: 80, reqAgi: 40, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 15, wizRaise: 0, speed: 0, luck: false, value: 2000, icon: 52, healHp: 0,   healMp: 0 },
  { id: 60, name: "Alas de Élite",        type: "wing",    class: "all",  slot: "wings",       level: 20, reqStr: 150, reqAgi: 150, reqVit: 50, reqEne: 150, attackMin: 10, attackMax: 20, defense: 15, wizRaise: 15, speed: 10, luck: false, value: 15000, icon: 63, healHp: 0,   healMp: 0 },
  { id: 61, name: "Casco de Élite",       type: "armor",   class: "dk",   slot: "head",        level: 18, reqStr: 160, reqAgi: 80, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 20, wizRaise: 0, speed: 0, luck: false, value: 5000, icon: 53, healHp: 0,   healMp: 0 },
  { id: 62, name: "Armadura de Élite",    type: "armor",   class: "dk",   slot: "chest",       level: 18, reqStr: 180, reqAgi: 80, reqVit: 0, reqEne: 0, attackMin: 0,  attackMax: 0,  defense: 35, wizRaise: 0, speed: 0, luck: false, value: 12000, icon: 54, healHp: 0,   healMp: 0 },
  { id: 63, name: "Espada Legendaria",    type: "weapon",  class: "dk",   slot: "twoHand",     level: 18, reqStr: 160, reqAgi: 80, reqVit: 0, reqEne: 0, attackMin: 48, attackMax: 72, defense: 0, wizRaise: 0, speed: 30, luck: true, value: 10000, icon: 55, healHp: 0,   healMp: 0 },
  { id: 64, name: "Arco Legendario",      type: "weapon",  class: "elf",  slot: "rightHand",   level: 18, reqStr: 50, reqAgi: 180, reqVit: 0, reqEne: 0, attackMin: 45, attackMax: 68, defense: 0, wizRaise: 0, speed: 40, luck: true, value: 10000, icon: 56, healHp: 0,   healMp: 0 },
  { id: 65, name: "Bastón Legendario",    type: "weapon",  class: "mago", slot: "rightHand",   level: 18, reqStr: 40, reqAgi: 0,  reqVit: 0, reqEne: 220,attackMin: 42, attackMax: 64, defense: 0, wizRaise: 60, speed: 25, luck: true, value: 10000, icon: 57, healHp: 0,   healMp: 0 },
];

// ---- SKILLS ----
const skills = [
  { id: 1,  name: "Ataque Normal",     class: "all",  levelReq: 0,  manaCost: 0,  agCost: 0, cooldown: 0,    damageModifier: 1.0, range: 1, areaOfEffect: 0, description: "Ataque básico cuerpo a cuerpo" },
  { id: 2,  name: "Slash",             class: "dk",   levelReq: 3,  manaCost: 5,  agCost: 0, cooldown: 2000, damageModifier: 1.5, range: 1, areaOfEffect: 0, description: "Corte poderoso con espada" },
  { id: 3,  name: "Whirlwind",         class: "dk",   levelReq: 10, manaCost: 15, agCost: 0, cooldown: 5000, damageModifier: 1.2, range: 1, areaOfEffect: 2, description: "Ataque giratorio de área" },
  { id: 4,  name: "Fury Strike",       class: "dk",   levelReq: 20, manaCost: 30, agCost: 0, cooldown: 8000, damageModifier: 2.0, range: 1, areaOfEffect: 0, description: "Golpe de furia devastador" },
  { id: 5,  name: "Sword Wave",        class: "dk",   levelReq: 15, manaCost: 20, agCost: 0, cooldown: 6000, damageModifier: 1.3, range: 3, areaOfEffect: 0, description: "Onda de energía de espada" },
  { id: 6,  name: "Impale",            class: "dk",   levelReq: 25, manaCost: 40, agCost: 0, cooldown: 10000, damageModifier: 2.5, range: 1, areaOfEffect: 0, description: "Empalamiento crítico" },
  { id: 7,  name: "Flecha",            class: "elf",  levelReq: 3,  manaCost: 5,  agCost: 0, cooldown: 1500, damageModifier: 1.4, range: 4, areaOfEffect: 0, description: "Disparo de flecha a distancia" },
  { id: 8,  name: "Multi Shot",        class: "elf",  levelReq: 10, manaCost: 12, agCost: 0, cooldown: 4000, damageModifier: 1.1, range: 4, areaOfEffect: 2, description: "Dispara múltiples flechas" },
  { id: 9,  name: "Heal",              class: "elf",  levelReq: 5,  manaCost: 10, agCost: 0, cooldown: 6000, damageModifier: 0.0, range: 0, areaOfEffect: 0, description: "Cura HP propio" },
  { id: 10, name: "Penetrating Arrow",  class: "elf",  levelReq: 15, manaCost: 18, agCost: 0, cooldown: 5000, damageModifier: 1.8, range: 5, areaOfEffect: 0, description: "Flecha que penetra armaduras" },
  { id: 11, name: "Summon Eagle",      class: "elf",  levelReq: 20, manaCost: 25, agCost: 0, cooldown: 30000, damageModifier: 0.0, range: 0, areaOfEffect: 0, description: "Invoca un águila de ataque" },
  { id: 12, name: "Ice Arrow",         class: "elf",  levelReq: 25, manaCost: 30, agCost: 0, cooldown: 8000, damageModifier: 2.0, range: 5, areaOfEffect: 0, description: "Flecha de hielo congelante" },
  { id: 13, name: "Bola de Fuego",     class: "mago", levelReq: 3,  manaCost: 10, agCost: 0, cooldown: 2000, damageModifier: 1.6, range: 5, areaOfEffect: 0, description: "Proyectil de fuego" },
  { id: 14, name: "Meteor Strike",     class: "mago", levelReq: 10, manaCost: 25, agCost: 0, cooldown: 5000, damageModifier: 2.0, range: 5, areaOfEffect: 2, description: "Lluvia de meteoritos" },
  { id: 15, name: "Ice Storm",         class: "mago", levelReq: 15, manaCost: 20, agCost: 0, cooldown: 4000, damageModifier: 1.5, range: 4, areaOfEffect: 2, description: "Tormenta de hielo" },
  { id: 16, name: "Lightning Bolt",    class: "mago", levelReq: 8,  manaCost: 15, agCost: 0, cooldown: 3000, damageModifier: 1.8, range: 5, areaOfEffect: 0, description: "Rayo eléctrico" },
  { id: 17, name: "Poison Cloud",      class: "mago", levelReq: 12, manaCost: 18, agCost: 0, cooldown: 6000, damageModifier: 1.3, range: 4, areaOfEffect: 2, description: "Nube venenosa" },
  { id: 18, name: "Teleport",          class: "mago", levelReq: 20, manaCost: 30, agCost: 0, cooldown: 10000, damageModifier: 0.0, range: 0, areaOfEffect: 0, description: "Teletransportación" },
  { id: 19, name: "Inferno",           class: "mago", levelReq: 25, manaCost: 40, agCost: 0, cooldown: 10000, damageModifier: 2.5, range: 5, areaOfEffect: 3, description: "Explosión infernal masiva" },
  { id: 20, name: "Energy Ball",       class: "mago", levelReq: 1,  manaCost: 8,  agCost: 0, cooldown: 1500, damageModifier: 1.3, range: 4, areaOfEffect: 0, description: "Bola de energía básica" },
  { id: 21, name: "Defense Up",        class: "dk",   levelReq: 8,  manaCost: 10, agCost: 0, cooldown: 120000, damageModifier: 0.0, range: 0, areaOfEffect: 0, description: "Aumenta defensa temporalmente" },
  { id: 22, name: "Power Up",          class: "dk",   levelReq: 12, manaCost: 15, agCost: 0, cooldown: 120000, damageModifier: 0.0, range: 0, areaOfEffect: 0, description: "Aumenta ataque temporalmente" },
  { id: 23, name: "Bless",             class: "elf",  levelReq: 15, manaCost: 20, agCost: 0, cooldown: 60000, damageModifier: 0.0, range: 0, areaOfEffect: 3, description: "Bendición de grupo" },
  { id: 24, name: "Shield",            class: "elf",  levelReq: 10, manaCost: 15, agCost: 0, cooldown: 30000, damageModifier: 0.0, range: 0, areaOfEffect: 0, description: "Escudo protector" },
  { id: 25, name: "Mana Shield",       class: "mago", levelReq: 8,  manaCost: 20, agCost: 0, cooldown: 60000, damageModifier: 0.0, range: 0, areaOfEffect: 0, description: "Escudo de maná que absorbe daño" },
  { id: 26, name: "Blizzard",          class: "mago", levelReq: 30, manaCost: 50, agCost: 0, cooldown: 15000, damageModifier: 2.2, range: 6, areaOfEffect: 3, description: "Ventisca devastadora" },
  { id: 27, name: "Comet",             class: "mago", levelReq: 18, manaCost: 28, agCost: 0, cooldown: 7000, damageModifier: 1.9, range: 5, areaOfEffect: 1, description: "Cometa de fuego" },
  { id: 28, name: "Triple Shot",       class: "elf",  levelReq: 20, manaCost: 22, agCost: 0, cooldown: 6000, damageModifier: 1.5, range: 5, areaOfEffect: 0, description: "Triple disparo" },
  { id: 29, name: "Cyclone",           class: "dk",   levelReq: 30, manaCost: 35, agCost: 0, cooldown: 12000, damageModifier: 1.8, range: 2, areaOfEffect: 3, description: "Torbellino de cuchillas" },
  { id: 30, name: "Evasion",           class: "elf",  levelReq: 25, manaCost: 15, agCost: 0, cooldown: 60000, damageModifier: 0.0, range: 0, areaOfEffect: 0, description: "Aumenta evasión temporalmente" },
];

// ---- NPCS ----
const npcs = [
  { id: 1, name: "Hanzo",            mapId: 1, x: 10, y: 15, shopItems: [7, 8, 9, 10, 11] },
  { id: 2, name: "Macey",            mapId: 1, x: 12, y: 15, shopItems: [12, 13, 14, 15, 16] },
  { id: 3, name: "Sage",             mapId: 1, x: 14, y: 15, shopItems: [17, 18, 19, 20, 21] },
  { id: 4, name: "Potion Girl",      mapId: 1, x: 16, y: 15, shopItems: [1, 2, 3, 4, 5, 6, 58] },
  { id: 5, name: "Armor Merchant",   mapId: 1, x: 8,  y: 18, shopItems: [22, 23, 24, 25, 26, 42] },
  { id: 6, name: "Weapon Smith",     mapId: 1, x: 18, y: 10, shopItems: [7, 8, 12, 17, 50, 51] },
  { id: 7, name: "Ring Merchant",    mapId: 2, x: 20, y: 18, shopItems: [52, 53, 54, 55, 56] },
  { id: 8, name: "Jeweler",          mapId: 1, x: 20, y: 15, shopItems: [47, 48, 49] },
  { id: 9, name: "Wing Merchant",    mapId: 3, x: 30, y: 30, shopItems: [44, 45, 46, 60] },
];

// ---- MAPS ----
const maps = [
  { id: 1,  name: "Lorencia",     width: 80,  height: 80,  spawnPoints: [{ monsterDefId: 1,  x: 20, y: 20, count: 5 }, { monsterDefId: 2,  x: 30, y: 25, count: 4 }, { monsterDefId: 16, x: 15, y: 15, count: 3 }, { monsterDefId: 25, x: 25, y: 30, count: 3 }, { monsterDefId: 30, x: 35, y: 20, count: 2 }],  npcs: [1, 2, 3, 4, 5, 6, 8], connections: [{ mapId: 2, x: 79, y: 40 }, { mapId: 3, x: 40, y: 79 }] },
  { id: 2,  name: "Davias",        width: 80,  height: 80,  spawnPoints: [{ monsterDefId: 3,  x: 20, y: 20, count: 5 }, { monsterDefId: 4,  x: 30, y: 30, count: 4 }, { monsterDefId: 30, x: 40, y: 25, count: 3 }, { monsterDefId: 5,  x: 25, y: 35, count: 2 }], npcs: [7], connections: [{ mapId: 1, x: 0, y: 40 }, { mapId: 4, x: 79, y: 40 }] },
  { id: 3,  name: "Noria",         width: 80,  height: 80,  spawnPoints: [{ monsterDefId: 6,  x: 20, y: 20, count: 5 }, { monsterDefId: 7,  x: 30, y: 30, count: 3 }, { monsterDefId: 8,  x: 35, y: 25, count: 3 }], npcs: [9], connections: [{ mapId: 1, x: 40, y: 0 }, { mapId: 5, x: 79, y: 40 }] },
  { id: 4,  name: "Dungeon",       width: 60,  height: 60,  spawnPoints: [{ monsterDefId: 9,  x: 15, y: 15, count: 6 }, { monsterDefId: 17, x: 25, y: 20, count: 4 }, { monsterDefId: 18, x: 20, y: 30, count: 4 }, { monsterDefId: 10, x: 30, y: 25, count: 3 }], npcs: [], connections: [{ mapId: 2, x: 0, y: 40 }] },
  { id: 5,  name: "Lost Tower 1",  width: 40,  height: 60,  spawnPoints: [{ monsterDefId: 11, x: 15, y: 15, count: 4 }, { monsterDefId: 19, x: 20, y: 25, count: 3 }, { monsterDefId: 12, x: 25, y: 20, count: 2 }], npcs: [], connections: [{ mapId: 3, x: 0, y: 40 }, { mapId: 6, x: 20, y: 59 }] },
  { id: 6,  name: "Lost Tower 2",  width: 40,  height: 60,  spawnPoints: [{ monsterDefId: 13, x: 15, y: 15, count: 4 }, { monsterDefId: 20, x: 20, y: 25, count: 3 }, { monsterDefId: 21, x: 25, y: 20, count: 2 }], npcs: [], connections: [{ mapId: 5, x: 20, y: 0 }, { mapId: 7, x: 20, y: 59 }] },
  { id: 7,  name: "Lost Tower 3",  width: 40,  height: 60,  spawnPoints: [{ monsterDefId: 22, x: 15, y: 15, count: 4 }, { monsterDefId: 14, x: 20, y: 25, count: 3 }, { monsterDefId: 23, x: 25, y: 20, count: 2 }], npcs: [], connections: [{ mapId: 8, x: 20, y: 59 }, { mapId: 6, x: 20, y: 0 }] },
  { id: 8,  name: "Lost Tower 4",  width: 40,  height: 60,  spawnPoints: [{ monsterDefId: 15, x: 15, y: 15, count: 4 }, { monsterDefId: 24, x: 20, y: 25, count: 3 }, { monsterDefId: 26, x: 25, y: 20, count: 2 }], npcs: [], connections: [{ mapId: 7, x: 20, y: 0 }, { mapId: 9, x: 20, y: 59 }] },
  { id: 9,  name: "Lost Tower 5",  width: 40,  height: 60,  spawnPoints: [{ monsterDefId: 27, x: 15, y: 15, count: 3 }, { monsterDefId: 28, x: 20, y: 25, count: 2 }, { monsterDefId: 29, x: 25, y: 20, count: 2 }], npcs: [], connections: [{ mapId: 8, x: 20, y: 0 }, { mapId: 10, x: 20, y: 59 }] },
  { id: 10, name: "Lost Tower 6",  width: 40,  height: 60,  spawnPoints: [{ monsterDefId: 31, x: 15, y: 15, count: 3 }, { monsterDefId: 32, x: 20, y: 25, count: 2 }, { monsterDefId: 33, x: 25, y: 20, count: 2 }], npcs: [], connections: [{ mapId: 9, x: 20, y: 0 }, { mapId: 11, x: 20, y: 59 }] },
  { id: 11, name: "Lost Tower 7",  width: 40,  height: 60,  spawnPoints: [{ monsterDefId: 34, x: 15, y: 15, count: 3 }, { monsterDefId: 35, x: 20, y: 25, count: 2 }, { monsterDefId: 36, x: 25, y: 20, count: 1 }], npcs: [], connections: [{ mapId: 10, x: 20, y: 0 }] },
  { id: 12, name: "Atlans",        width: 60,  height: 60,  spawnPoints: [{ monsterDefId: 8,  x: 20, y: 20, count: 5 }, { monsterDefId: 17, x: 30, y: 25, count: 3 }, { monsterDefId: 31, x: 25, y: 30, count: 3 }], npcs: [], connections: [{ mapId: 2, x: 0, y: 20 }] },
  { id: 13, name: "Icarus",        width: 60,  height: 60,  spawnPoints: [{ monsterDefId: 33, x: 20, y: 20, count: 4 }, { monsterDefId: 35, x: 30, y: 25, count: 3 }, { monsterDefId: 36, x: 35, y: 30, count: 2 }], npcs: [], connections: [{ mapId: 3, x: 0, y: 20 }] },
];

// ---- CLASSES ----
const classes = [
  { id: "dark_knight", name: "Dark Knight", baseStats: { str: 28, agi: 20, vit: 25, ene: 10 }, pointsPerLevel: 5, hpPerLevel: 12, mpPerLevel: 4, skills: [1, 2, 3, 4, 5, 6, 21, 22, 29] },
  { id: "elf",         name: "Elf",         baseStats: { str: 22, agi: 28, vit: 20, ene: 13 }, pointsPerLevel: 5, hpPerLevel: 8,  mpPerLevel: 6, skills: [1, 7, 8, 9, 10, 11, 12, 23, 24, 28, 30] },
  { id: "mago",        name: "Mago",        baseStats: { str: 18, agi: 18, vit: 15, ene: 32 }, pointsPerLevel: 5, hpPerLevel: 6,  mpPerLevel: 10, skills: [1, 13, 14, 15, 16, 17, 18, 19, 20, 25, 26, 27] },
];

// Write all files
fs.writeFileSync('/docker/muOnline/server/MuServer/json/classes.json', JSON.stringify(classes, null, 2));
fs.writeFileSync('/docker/muOnline/server/MuServer/json/monsters.json', JSON.stringify(monsters, null, 2));
fs.writeFileSync('/docker/muOnline/server/MuServer/json/items.json', JSON.stringify(items, null, 2));
fs.writeFileSync('/docker/muOnline/server/MuServer/json/skills.json', JSON.stringify(skills, null, 2));
fs.writeFileSync('/docker/muOnline/server/MuServer/json/npcs.json', JSON.stringify(npcs, null, 2));
fs.writeFileSync('/docker/muOnline/server/MuServer/json/maps.json', JSON.stringify(maps, null, 2));

console.log("Done! All 6 JSON files written with correct format.");
